name: Flask Tests

on:
  push:
    branches-ignore:
      - main  # Run on pushes to all branches except main
  pull_request:
    branches:
      - main  # Run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Latest checkout action
      with:
        fetch-depth: 1  # Shallow clone for faster checkout

    - name: Set up Python 3.11
      uses: actions/setup-python@v5  # Latest Python setup action
      with:
        python-version: "3.11"
        cache: "pip"  # Enable pip cache

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ -v --color=yes
