name: Flask Tests

on:
  push:
    branches-ignore:
      - main  # Run on pushes to all branches except main
  pull_request:
    branches:
      - main  # Run on PRs targeting main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: test
      run: |
        pytest tests/ -v --color=yes

    - name: Auto-merge PR
      if: |
        github.event_name == 'pull_request' && 
        steps.test.outcome == 'success' && 
        github.event.pull_request.base.ref == 'main'
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_METHOD: "merge"
        MERGE_DELETE_BRANCH: "false"
        MERGE_COMMIT_MESSAGE: "Auto-merge PR #{number} after successful tests 🎉"
